[[pages]]
path = "pages/Examples/example2.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/Examples/example.py"
name = "Page 2"
icon = ":books:"

[[pages]]
name = "My section"
icon = "ğŸˆï¸"
is_section = true

# Pages after an `is_section = true` will be indented
[[pages]]
name = "Another page"
icon = "ğŸ’ª"